### PR TITLE
added alm_POST function with X-HTTP-Method-Override: GET header

### PR DESCRIPTION
**Pull request by mfenner**
Allowing a larger payload, e.g. with a list of 50 URLs.

### CODE REVIEW

**Comment by mfenner** [comment]
```
Error in vapply(tt$data, function(x) x$doi, character(1)) : 
  Werte müssen die Länge 1 haben,
Ergebnis von FUN(X[[1]]) hat aber Länge 0
```
Excuse the German. Seems that the function expects a DOI value, which is not always present.

**Comment by sckott** [comment]
@mfenner what was the call that caused that error?

**Comment by mfenner** [comment]
```
require("alm")
urls <- c("https://github.com/najoshi/sickle","https://github.com/lh3/wgsim","https://github.com/jstjohn/SeqPrep")
alm <- alm_ids(url = urls, api_url = "http://software.lagotto.io/api/v5/articles")
```

**Comment by sckott** [comment]
thanks @mfenner , looking

**Comment by sckott** [comment]
@mfenner figured it out, i'll just merge this, then patch the problem, then push back up

**Pull request merged**
