### PR TITLE
Put link to CONDUCT.md in inst/; add primary one to .Rbuildignore

### PR DESCRIPTION
**Pull request by diana-ly**
Karl Broman recommended the edit to 'to avoid a note about "Non-standard file/directory found at top level"'

### CODE REVIEW

**Comment by sckott** [comment]
thanks, curious why the conduct.md file in `inst/` ?

**Comment by diana-ly** [comment]
Here's Karl's explanation: 
R CMD check gives a "Note" about the CONDUCT.md file, "Non-standard file/directory found at top level".

To avoid that, I put a symbolic link to the file within inst/ and then added ^CONDUCT.md$ to the .Rbuildignore file.

**Comment by sckott** [comment]
> a symbolic link to the file within inst/ 

i don't think this is needed, or am I wrong?

**Comment by karthik** [comment]
I'm also just as confused as you, Scott.  @kbroman suggests that by adding it to `inst/`, then the file also becomes available on the CRAN bundle. 

The way I see it, the conduct is for contributing to the development of the package itself, not using the software. So to me it doesn't matter that this file remains available on CRAN. As long as someone sees the link to contribute on the DESCRIPTION file, they will end up at the repo where this file will be.

**Comment by kbroman** [comment]
@karthik @sckott I'll go along with this: put `^CONDUCT.md$` in `.Rbuildignore` and ignore my suggestion about `inst/`.

**Comment by sckott** [comment]
thanks all!

@diana-ly can you:

- remove the inst/conduct file added in your PR
- also, the line in `.Rbuildignore` is `+^CONDUCT.md$`, remove that `+` at the beginning

then good to go

**Comment by sckott** [comment]
thanks @diana-ly !

**Pull request merged**
