### PR TITLE
more variable name changes

### PR DESCRIPTION
**Pull request by mfenner**

### CODE REVIEW

**Comment by mfenner** [comment]
Getting the following error:

```
Error in alm_GET(api_url, c(args, ids = id2), sleep = sleep, ...) : 
  client error: (414) Request-URI Too Long
```
Presumably 50 identifiers is too much when using URLs. Should I go down to 25, or is there another way to work around this?

**Comment by sckott** [comment]
@mfenner 50 could be too long depending on how long the id strings are, yeah, 25 sounds good

**Comment by sckott** [comment]
@mfenner hmmm, travis is fine, but the windows builder doesn't like a character https://ci.appveyor.com/project/sckott/alm/build/1.0.280#L386 so not a big deal, i'll merge and play around locally

**Comment by mfenner** [comment]
This needs more work. I have tried to `URLencode` the URL, and that seems to make the `414` error go away, but still not ok. Please have a look.

**Comment by sckott** [comment]
@mfenner yep, will do now

**Comment by sckott** [comment]
@mfenner do you want to support `POST` requests? that would be one way around the URI too long problem

**Comment by mfenner** [comment]
I was thinking along the same lines. What works without changes in the Lagotto software is the following:

```
curl -X POST -d "ids=https://github.com/najoshi/sickle,https://github.com/lh3/wgsim,https://github.com/jstjohn/SeqPrep&type=url" -H "X-HTTP-Method-Override: GET" "http://software.lagotto.io/api/v5/articles" 
```

In other words, do a POST with the ids in the body, and then use `X-HTTP-Method-Override` to say it is a GET request. Can you simulate this in your R code?

**Comment by sckott** [comment]
@mfenner okay, pushed a bunch of fixes, try again

for the POST method, i'll test it out soon...

**Comment by mfenner** [comment]
@sckott I have implemented POST in #48. Looks almost too easy, but seems to work.

**Pull request merged**
